# Generated by Django 4.2.5 on 2023-09-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publish_year", models.IntegerField()),
                ("origin_price", models.FloatField()),
                ("all_data", models.JSONField(default=list)),
                ("back_data", models.JSONField(default=list)),
                ("cover_data", models.JSONField(default=list)),
                ("side_data", models.JSONField(default=list)),
            ],
        ),
    ]
